import { Copy, Crown, Globe2, Link2, Lock, Settings2, Shield, UserMinus, UserPlus, UserRound, X } from "lucide-react"
import { useCallback, useEffect, useState } from "react"
import { chatApi } from "../../api/chatApi"
import type { Chat, ChatMemberInfo, ChatPermission } from "../../models/chat"
import { useAuthStore } from "../../store/authStore"

type Tab = "members" | "settings"
const PERMISSIONS: { id: ChatPermission; label: string }[] = [
  { id: "messages", label: "Xabar yuborish" }, { id: "media", label: "Media yuborish" },
  { id: "links", label: "Havola yuborish" }, { id: "members", label: "A'zo qo'shish" },
  { id: "info", label: "Ma'lumotni tahrirlash" }, { id: "pin", label: "Xabarni mahkamlash" },
]
export function MembersDialog({ chatId, onClose }: { chatId: number; onClose: (left?: boolean) => void }) {
  const myId = useAuthStore((store) => store.user?.id ?? 0)
  const [members, setMembers] = useState<ChatMemberInfo[]>([]), [chat, setChat] = useState<Chat | null>(null)
  const [tab, setTab] = useState<Tab>("members"), [username, setUsername] = useState(""), [busy, setBusy] = useState(false)
  const [title, setTitle] = useState(""), [about, setAbout] = useState(""), [publicChat, setPublicChat] = useState(false), [handle, setHandle] = useState("")
  const [invite, setInvite] = useState(""), [permissions, setPermissions] = useState<Record<ChatPermission, boolean>>({ messages: true, media: true, links: true, members: false, info: false, pin: false })
  const load = useCallback(async () => { const [nextMembers, nextChat] = await Promise.all([chatApi.members(chatId), chatApi.get(chatId)]); setMembers(nextMembers); setChat(nextChat); setTitle(nextChat.title); setAbout(nextChat.about); setPublicChat(nextChat.is_public); setHandle(nextChat.username); setInvite(await chatApi.inviteLink(chatId)) }, [chatId])
  useEffect(() => { void load() }, [load])
  const canManage = members.some((member) => member.user_id === myId && member.role !== "member")
  const run = async (action: () => Promise<void>) => { setBusy(true); try { await action(); await load() } finally { setBusy(false) } }
  const add = () => { const clean = username.trim().replace(/^@/, ""); if (clean) void run(async () => { await chatApi.addMember(chatId, clean); setUsername("") }) }
  const save = () => void run(() => chatApi.update(chatId, { title: title.trim(), about: about.trim(), is_public: publicChat, username: publicChat ? handle : "", permissions }))
  return <div className="fixed inset-0 z-[999] flex items-end justify-center bg-black/40 backdrop-blur-xl sm:items-center sm:p-4" onClick={() => onClose()}><div className="liquid-card max-h-[92dvh] w-full max-w-lg overflow-hidden rounded-b-none p-4 sm:rounded-[24px] sm:p-5" onClick={(event) => event.stopPropagation()}>
    <div className="mb-3 flex items-center justify-between"><div><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-accent">{chat?.type === "channel" ? "Kanal" : "Guruh"} boshqaruvi</p><h2 className="text-lg font-bold text-ink">{chat?.title || "Sozlamalar"}</h2></div><button onClick={() => onClose()} className="icon-btn pressable grid h-9 w-9 place-items-center rounded-full"><X className="h-4 w-4" /></button></div>
    <div className="liquid-control mb-3 flex rounded-[13px] p-1"><button onClick={() => setTab("members")} className={`flex-1 rounded-[10px] py-2 text-[11px] font-bold ${tab === "members" ? "bg-surface text-accent shadow-sm" : "text-muted"}`}>A'zolar {members.length}</button><button onClick={() => setTab("settings")} className={`flex flex-1 items-center justify-center gap-1 rounded-[10px] py-2 text-[11px] font-bold ${tab === "settings" ? "bg-surface text-accent shadow-sm" : "text-muted"}`}><Settings2 className="h-3.5 w-3.5" /> Sozlamalar</button></div>
    {tab === "members" ? <div>{canManage && <div className="liquid-control mb-2.5 flex gap-2 rounded-[13px] p-1 pl-3"><UserPlus className="my-auto h-4 w-4 text-muted" /><input value={username} onChange={(event) => setUsername(event.target.value)} onKeyDown={(event) => event.key === "Enter" && add()} placeholder="@username orqali qo'shish" className="min-w-0 flex-1 bg-transparent text-[12px] outline-none" /><button onClick={add} disabled={busy} className="rounded-[10px] bg-accent px-3 text-[10px] font-bold text-white">Qo'shish</button></div>}<ul className="scroll-clean max-h-[48dvh] space-y-1.5 overflow-y-auto">{members.map((member) => <li key={member.user_id} className="flex items-center gap-2.5 rounded-[14px] bg-surface/60 p-2"><span className="glass-key grid h-10 w-10 shrink-0 place-items-center rounded-[13px] text-muted"><UserRound className="h-4 w-4" /></span><span className="min-w-0 flex-1"><b className="block truncate text-[12px] text-ink">{member.display_name}</b><span className="text-[9px] text-muted">@{member.username}</span></span>{member.role !== "member" && <span className="rounded-full bg-accent/10 px-2 py-1 text-[8px] font-bold uppercase text-accent">{member.role}</span>}{canManage && member.role !== "creator" && member.user_id !== myId && <><button title={member.role === "admin" ? "Adminlikdan olish" : "Admin qilish"} onClick={() => void run(() => chatApi.setRole(chatId, member.user_id, member.role === "admin" ? "member" : "admin"))} className="grid h-8 w-8 place-items-center rounded-[10px] text-accent hover:bg-accent/10">{member.role === "admin" ? <Shield className="h-4 w-4" /> : <Crown className="h-4 w-4" />}</button><button title="O'chirish" onClick={() => void run(() => chatApi.removeMember(chatId, member.user_id))} className="grid h-8 w-8 place-items-center rounded-[10px] text-danger hover:bg-danger/10"><UserMinus className="h-4 w-4" /></button></>}</li>)}</ul></div> : <div className="scroll-clean max-h-[58dvh] space-y-3 overflow-y-auto pr-1"><input value={title} onChange={(event) => setTitle(event.target.value)} className="liquid-control w-full rounded-[14px] px-3 py-2.5 text-[12px] outline-none" placeholder="Nomi" /><textarea value={about} onChange={(event) => setAbout(event.target.value)} className="liquid-control w-full resize-none rounded-[14px] px-3 py-2.5 text-[12px] outline-none" rows={2} placeholder="Tavsif" />
      <div className="grid grid-cols-2 gap-2"><button onClick={() => setPublicChat(true)} className={`rounded-[15px] p-3 text-left ${publicChat ? "bg-accent text-white" : "bg-surfaceHi text-muted"}`}><Globe2 className="mb-1 h-4 w-4" /><b className="text-[11px]">Ommaviy</b></button><button onClick={() => setPublicChat(false)} className={`rounded-[15px] p-3 text-left ${!publicChat ? "bg-accent text-white" : "bg-surfaceHi text-muted"}`}><Lock className="mb-1 h-4 w-4" /><b className="text-[11px]">Yopiq</b></button></div>
      {publicChat ? <label className="block text-[10px] font-bold text-muted">Username<div className="liquid-control mt-1 flex rounded-[14px] px-3"><span className="py-2.5 text-accent">@</span><input value={handle} onChange={(event) => setHandle(event.target.value.replace(/[^a-zA-Z0-9_]/g, ""))} className="min-w-0 flex-1 bg-transparent py-2.5 text-[12px] outline-none" /></div></label> : <div className="rounded-[14px] bg-surfaceHi p-3"><p className="mb-1 text-[9px] font-bold text-muted">TAKLIF HAVOLASI</p><div className="flex items-center gap-2"><Link2 className="h-4 w-4 text-accent" /><span className="min-w-0 flex-1 truncate text-[11px] text-ink">{invite}</span><button onClick={() => void navigator.clipboard?.writeText(invite)}><Copy className="h-4 w-4 text-muted" /></button></div><button onClick={() => void run(async () => setInvite(await chatApi.inviteLink(chatId, true)))} className="mt-2 text-[10px] font-bold text-accent">Yangi havola yaratish</button></div>}
      <div><p className="mb-1 text-[9px] font-bold uppercase text-muted">Granular ruxsatlar</p>{PERMISSIONS.map((item) => <button key={item.id} onClick={() => setPermissions((current) => ({ ...current, [item.id]: !current[item.id] }))} className="mt-1 flex w-full items-center justify-between rounded-[13px] bg-surface/60 px-3 py-2 text-[11px] font-semibold text-ink"><span>{item.label}</span><span className={`h-6 w-10 rounded-full p-1 ${permissions[item.id] ? "bg-accent" : "bg-line"}`}><i className={`block h-4 w-4 rounded-full bg-white transition ${permissions[item.id] ? "translate-x-4" : ""}`} /></span></button>)}</div><button onClick={save} disabled={busy || !title.trim()} className="w-full rounded-[14px] bg-accent py-3 text-[11px] font-bold text-white disabled:opacity-40">Saqlash</button></div>}
    <button onClick={() => void run(async () => { await chatApi.leave(chatId); onClose(true) })} disabled={busy} className="mt-3 w-full rounded-[13px] bg-danger/10 py-2.5 text-[11px] font-semibold text-danger">Suhbatdan chiqish</button>
  </div></div>
}
