import { ArrowLeft,Play,Radio,UsersRound } from "lucide-react"
import { useEffect,useState } from "react"
import { useNavigate } from "react-router-dom"
import { Routes } from "../../app/routes"
import { roomsApi } from "../../api/roomsApi"
import { categoryTitleFor,type CatalogCategory,type CatalogItem } from "../../models/catalog"
import { gameDescription,gameTitle,type GameManifest } from "../../models/marketplace"
import { useAuthStore } from "../../store/authStore"
import { useCatalogStore } from "../../store/catalogStore"
import { ExerciseFinder } from "./ExerciseFinder"
import { firstGameLeaf,GameCatalogBrowser } from "./GameCatalogBrowser"
import { marketplaceIcon } from "./marketplaceIcons"
import { MatchSetup,type MatchMode } from "./MatchSetup"
export function GameDetails({game,onBack}:{game:GameManifest;onBack:()=>void}){
 const navigate=useNavigate(),locale=useAuthStore(s=>s.user?.locale??"en"),{tree,load}=useCatalogStore()
 const [subject,setSubject]=useState<CatalogCategory|null>(null),[exercise,setExercise]=useState<CatalogItem|null>(null)
 const [mode,setMode]=useState<MatchMode>(game.supportsSolo?"solo":"duo"),[maxPlayers,setMaxPlayers]=useState(Math.min(4,game.maxPlayers)),[level,setLevel]=useState(2),[timeLimit,setTimeLimit]=useState(120),[busy,setBusy]=useState(false),[error,setError]=useState("")
 useEffect(()=>{void load()},[load]);const chosen=subject??firstGameLeaf(tree,game.gameKind)
 const start=async()=>{if(game.status!=="live"||!chosen)return;setBusy(true);setError("");try{if(game.gameKind==="typing"){navigate(Routes.practice,{state:{category:chosen.code,title:exercise?.title||categoryTitleFor(chosen,locale),difficulty:level}});return}const created=await roomsApi.create({gameSlug:game.slug,kind:game.gameKind,subjectCode:chosen.code,exerciseId:exercise?.source==="exercise"?exercise.id:0,level,mode,maxPlayers:mode==="solo"?1:mode==="duo"?2:maxPlayers,timeLimitSec:timeLimit,hostPlays:true});if(!created.room.id)throw new Error("room");if(mode==="solo")await roomsApi.start(created.room.code);navigate(`${Routes.room}/${created.room.code}`)}catch{setError("Could not start this game. Please try again.")}finally{setBusy(false)}}
 return <div className="page-enter space-y-3.5"><button onClick={onBack} className="inline-flex items-center gap-1.5 text-[11px] font-bold text-muted hover:text-ink"><ArrowLeft className="h-4 w-4"/> All games</button><section className="liquid-card relative overflow-hidden p-4 sm:p-6"><span className="pointer-events-none absolute -right-20 -top-24 h-64 w-64 rounded-full opacity-20 blur-3xl" style={{backgroundColor:game.accent}}/><div className="relative flex items-start gap-4"><span className="glass-key grid h-14 w-14 shrink-0 place-items-center rounded-[18px] sm:h-16 sm:w-16" style={{color:game.accent}}>{marketplaceIcon(game.icon,"h-6 w-6")}</span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h1 className="text-[25px] font-extrabold tracking-ios text-ink sm:text-[34px]">{gameTitle(game,locale)}</h1><span className={`rounded-full px-2.5 py-1 text-[8px] font-bold uppercase ${game.status==="live"?"bg-mint/15 text-mint":"bg-amber/15 text-amber"}`}>{game.status}</span></div><p className="mt-1 max-w-2xl text-[11px] leading-relaxed text-muted sm:text-[13px]">{gameDescription(game,locale)}</p><div className="mt-2 flex gap-2 text-[9px] font-semibold text-muted">{game.supportsRealtime&&<span className="inline-flex items-center gap-1"><Radio className="h-3 w-3 text-mint"/> Real-time</span>}<span className="inline-flex items-center gap-1"><UsersRound className="h-3 w-3 text-accent"/> Up to {game.maxPlayers}</span></div></div></div></section><div className="grid gap-3.5 xl:grid-cols-[minmax(0,1.25fr)_minmax(300px,.75fr)]"><div className="space-y-3.5"><GameCatalogBrowser key={game.slug} tree={tree} gameKind={game.gameKind} locale={locale} selectedCode={chosen?.code??""} onSelect={v=>{setSubject(v);setExercise(null)}}/><ExerciseFinder gameKind={game.gameKind} categoryCode={chosen?.code??""} level={level} enabled={game.supportsSearch} selected={exercise} onSelect={setExercise}/></div><div className="space-y-3.5"><MatchSetup game={game} mode={mode} maxPlayers={maxPlayers} level={level} timeLimit={timeLimit} onMode={setMode} onMaxPlayers={setMaxPlayers} onLevel={setLevel} onTimeLimit={setTimeLimit}/><button disabled={busy||game.status!=="live"||!chosen} onClick={()=>void start()} className="pressable flex w-full items-center justify-center gap-2 rounded-[16px] bg-accent py-3.5 text-[12px] font-extrabold text-white shadow-glow disabled:opacity-45"><Play className="h-4 w-4" fill="currentColor"/>{busy?"Preparing...":game.status==="live"?mode==="solo"?"Start solo":"Create live room":"Beta preview"}</button>{error&&<p className="text-center text-[10px] text-danger">{error}</p>}</div></div></div>
}
