import { Radio,User,Users,UsersRound } from "lucide-react"
import type { ReactNode } from "react"
import type { GameManifest } from "../../models/marketplace"
export type MatchMode="solo"|"duo"|"multi"
export function MatchSetup({game,mode,maxPlayers,level,timeLimit,onMode,onMaxPlayers,onLevel,onTimeLimit}:{game:GameManifest;mode:MatchMode;maxPlayers:number;level:number;timeLimit:number;onMode:(v:MatchMode)=>void;onMaxPlayers:(v:number)=>void;onLevel:(v:number)=>void;onTimeLimit:(v:number)=>void}){
 const modes:[MatchMode,string,ReactNode][]=[["solo","Solo",<User/>],["duo","Duel",<Users/>],["multi","Party",<UsersRound/>]]
 return <section className="liquid-card p-4 sm:p-5"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-muted">Match setup</p><h2 className="text-[15px] font-extrabold text-ink">How do you want to play?</h2><div className="mt-3 grid grid-cols-3 gap-1.5">{modes.map(([id,label,icon])=>{const disabled=id==="solo"?!game.supportsSolo:!game.supportsRealtime;return <button key={id} disabled={disabled} onClick={()=>onMode(id)} className={`rounded-[14px] p-2.5 text-center disabled:opacity-30 ${mode===id?"bg-accent text-white shadow-glow":"bg-surfaceHi/70 text-muted"}`}><span className="mx-auto block w-fit [&>svg]:h-4 [&>svg]:w-4">{icon}</span><span className="mt-1 block text-[9px] font-bold">{label}</span></button>})}</div><div className="mt-4 space-y-3"><Slider label="Level" value={level} min={1} max={5} onChange={onLevel}/>{mode==="multi"&&<Slider label="Max players" value={maxPlayers} min={3} max={game.maxPlayers} onChange={onMaxPlayers}/>} {game.gameKind==="math"&&<div><p className="mb-1.5 text-[9px] font-bold text-muted">Round time</p><div className="grid grid-cols-3 gap-1.5">{[60,120,300].map(v=><button key={v} onClick={()=>onTimeLimit(v)} className={`rounded-[11px] py-2 text-[9px] font-bold ${timeLimit===v?"bg-ink text-surface":"bg-surfaceHi text-muted"}`}>{v/60} min</button>)}</div></div>}</div><p className="mt-3 flex items-center gap-1.5 text-[8px] font-semibold text-muted"><Radio className="h-3 w-3 text-mint"/> Answers are checked by the server. First correct finish wins.</p></section>
}
function Slider({label,value,min,max,onChange}:{label:string;value:number;min:number;max:number;onChange:(v:number)=>void}){return <label className="block"><span className="mb-1.5 flex justify-between text-[9px] font-bold text-muted"><span>{label}</span><span className="text-ink">{value}</span></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))} className="w-full accent-accent"/></label>}
