import { roomsApi } from "../../api/roomsApi"
import type { RoomInfo } from "../../models/room"
import { GlassCard } from "../../ui/GlassCard"
const MODES=[["solo","Solo"],["duo","Duel"],["multi","Party"]] as const
type Patch=Partial<Pick<RoomInfo,"mode"|"level"|"maxPlayers"|"timeLimitSec"|"hostPlays">>
export function RoomConfigBar({room,isHost,code}:{room:RoomInfo;isHost:boolean;code:string}){
 const apply=(p:Patch)=>{if(!isHost)return;void roomsApi.config(code,{gameSlug:room.gameSlug,kind:room.kind,subjectCode:room.subjectCode,exerciseId:room.exerciseId,level:p.level??room.level,mode:p.mode??room.mode,maxPlayers:p.maxPlayers??room.maxPlayers,timeLimitSec:p.timeLimitSec??room.timeLimitSec,hostPlays:p.hostPlays??room.hostPlays})}
 return <GlassCard><div className="mb-3"><p className="text-[9px] font-bold uppercase tracking-[.14em] text-muted">{room.gameSlug.replace(/-/g," ")}</p><h2 className="text-[17px] font-extrabold tracking-ios text-ink">Match setup</h2></div><div className="grid grid-cols-3 gap-2">{MODES.map(([id,label])=><button key={id} disabled={!isHost} onClick={()=>apply({mode:id})} className={`rounded-[13px] px-2 py-2.5 text-[10px] font-bold disabled:opacity-60 ${room.mode===id?"bg-accent text-white shadow-glow":"bg-surfaceHi/70 text-muted"}`}>{label}</button>)}</div><Step label="Level" value={room.level} disabled={!isHost} dec={()=>apply({level:room.level-1})} inc={()=>apply({level:room.level+1})}/>{room.mode==="multi"&&<Step label="Max players" value={room.maxPlayers} disabled={!isHost} dec={()=>apply({maxPlayers:room.maxPlayers-1})} inc={()=>apply({maxPlayers:room.maxPlayers+1})}/>}<Step label="Time (sec)" value={room.timeLimitSec} disabled={!isHost} dec={()=>apply({timeLimitSec:room.timeLimitSec-30})} inc={()=>apply({timeLimitSec:room.timeLimitSec+30})}/><div className="mt-3 flex items-center justify-between"><span className="text-[11px] font-semibold text-muted">Host plays</span><button disabled={!isHost} onClick={()=>apply({hostPlays:!room.hostPlays})} className={`h-6 w-11 rounded-full transition disabled:opacity-60 ${room.hostPlays?"bg-accent":"border border-line bg-surfaceHi"}`}><span className={`block h-5 w-5 rounded-full bg-white shadow transition-transform ${room.hostPlays?"translate-x-5":"translate-x-0.5"}`}/></button></div></GlassCard>
}
function Step({label,value,disabled,dec,inc}:{label:string;value:number;disabled:boolean;dec:()=>void;inc:()=>void}){return <div className="mt-3 flex items-center justify-between"><span className="text-[11px] font-semibold text-muted">{label}</span><div className="flex items-center gap-2"><button disabled={disabled} onClick={dec} className="grid h-7 w-7 place-items-center rounded-full bg-surfaceHi text-accent disabled:opacity-40">-</button><span className="min-w-[2rem] text-center text-[12px] font-extrabold text-ink">{value}</span><button disabled={disabled} onClick={inc} className="grid h-7 w-7 place-items-center rounded-full bg-surfaceHi text-accent disabled:opacity-40">+</button></div></div>}
